# Generated by Django 4.2.6 on 2023-10-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_remove_boss_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='number',
            field=models.CharField(default=1, help_text='Введите номер выплаты:', max_length=8, verbose_name='Номер выплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='payout',
            field=models.CharField(help_text='Внесите начальную ставку:', max_length=8, verbose_name='Ставка'),
        ),
    ]
