# Generated by Django 4.2.6 on 2023-10-20 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0008_remove_worker_contract_worker_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='contract',
            field=models.ForeignKey(default=1, help_text='Выберите договор:', on_delete=django.db.models.deletion.CASCADE, to='first_app.contract', verbose_name='name contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='id_user',
            field=models.ForeignKey(blank=True, help_text='выберите пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя'),
        ),
    ]
