# Generated by Django 4.2.6 on 2023-11-13 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0009_worker_contract_worker_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='id_user',
            field=models.ForeignKey(blank=True, help_text='выберите пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя'),
        ),
    ]
