# Generated by Django 4.2.6 on 2023-12-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_boss_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.IntegerField(help_text='выберите отдел', primary_key=True, serialize=False, verbose_name='id отдела'),
        ),
    ]
