# Generated by Django 4.2.6 on 2023-12-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_alter_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='departments',
        ),
        migrations.AddField(
            model_name='boss',
            name='departments',
            field=models.ManyToManyField(to='first_app.department'),
        ),
    ]
